r/aws_default_subnet: Full resource life cycle. First baby steps.
Acceptance test output:

% AWS_DEFAULT_REGION=eu-west-2 make testacc TESTARGS='-run=TestAccEC2DefaultSubnet_basic' PKG_NAME=internal/service/ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2DefaultSubnet_basic -timeout 180m
=== RUN   TestAccEC2DefaultSubnet_basic
=== PAUSE TestAccEC2DefaultSubnet_basic
=== CONT  TestAccEC2DefaultSubnet_basic
    default_subnet_test.go:17: Step 1/1 error: After applying this test step, the plan was not empty.
        stdout:

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_default_subnet.test will be updated in-place
          ~ resource "aws_default_subnet" "test" {
                id                                             = "subnet-5e636b26"
              ~ map_public_ip_on_launch                        = true -> false
                # (15 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccEC2DefaultSubnet_basic (10.19s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2        13.707s
FAIL
make: *** [testacc] Error 1